##########################################################
##################  所有profile共有的配置  #################
##########################################################


###################  项目启动端口  ###################
server:
  port: 81

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    time-zone: GMT+8
  devtools:
    restart:
      additional-paths: flowable-demo/src/main/java
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
###################  flowable配置  ##################
flowable:
# 关闭定时任务JOB
  async-executor-activate: false
management:
  endpoint:
    flowable:
      enabled: true
###################  mybatis配置  ###################
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:dao/*.xml
  type-aliases-package: tk.mybatis.springboot.vo

mapper:
  not-empty: false
  identity: MYSQL
  wrapKeyword: "`{0}`"

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
  datasource:
    url: jdbc:mysql://localhost:3306/flowable?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: sc
server:
  port: 81
---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: pro
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
  datasource:
    url: jdbc:mysql://localhost:3306/flowable?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: sc
server:
  port: 8080
...